version: '3'

services:
  php:
    #image: wordpress:5.9.0-fpm
    build: .
    volumes:
      - ../.vscode-server:/root/.vscode-server
      - ../.vscode-server-insiders:/root/.vscode-server-insiders
      - ../html:/var/www/html
      - ../bin:/root/bin
      - ../extra-php.ini:/usr/local/etc/php/conf.d/extra-php.ini
    ports:
      - 9000:9000
      - 8080:80
    restart: unless-stopped